[package]
name = "valor-example-basic"
version = "0.0.0"
authors = ["Jason Nall <jsonnull@gmail.com>"]
workspace = "../.."
edition = "2018"

[[bin]]
name = "valor-example-basic"
path = "main.rs"

[dependencies]
valor = { path = "../../src/valor" }
