[package]
name = "valor_camera"
version = "0.0.0-test"
authors = ["Jason Nall <jsonnull@gmail.com>"]
workspace = "../.."
edition = "2018"
description = "Ergonomic rendering engine for games in Rust."
license = "MIT"

[lib]
name = "valor_camera"
path = "src/lib.rs"

[dependencies]
cgmath = "0.15.0"
